// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// gibbs_ad_use_cpp
NumericVector gibbs_ad_use_cpp(Rcpp::NumericMatrix marginal, Rcpp::List tpq_list, Rcpp::List taq_list);
RcppExport SEXP _eratosthenes_gibbs_ad_use_cpp(SEXP marginalSEXP, SEXP tpq_listSEXP, SEXP taq_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type marginal(marginalSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type tpq_list(tpq_listSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type taq_list(taq_listSEXP);
    rcpp_result_gen = Rcpp::wrap(gibbs_ad_use_cpp(marginal, tpq_list, taq_list));
    return rcpp_result_gen;
END_RCPP
}
// gibbs_ad_use_init_cpp
NumericVector gibbs_ad_use_init_cpp(Rcpp::List tpq_list, Rcpp::List taq_list, int n_samples);
RcppExport SEXP _eratosthenes_gibbs_ad_use_init_cpp(SEXP tpq_listSEXP, SEXP taq_listSEXP, SEXP n_samplesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type tpq_list(tpq_listSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type taq_list(taq_listSEXP);
    Rcpp::traits::input_parameter< int >::type n_samples(n_samplesSEXP);
    rcpp_result_gen = Rcpp::wrap(gibbs_ad_use_init_cpp(tpq_list, taq_list, n_samples));
    return rcpp_result_gen;
END_RCPP
}
// quae_postea_matrix_cpp
Rcpp::IntegerMatrix quae_postea_matrix_cpp(int elem, Rcpp::List obj);
RcppExport SEXP _eratosthenes_quae_postea_matrix_cpp(SEXP elemSEXP, SEXP objSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type elem(elemSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type obj(objSEXP);
    rcpp_result_gen = Rcpp::wrap(quae_postea_matrix_cpp(elem, obj));
    return rcpp_result_gen;
END_RCPP
}
// quae_antea_matrix_cpp
Rcpp::IntegerMatrix quae_antea_matrix_cpp(int elem, Rcpp::List obj);
RcppExport SEXP _eratosthenes_quae_antea_matrix_cpp(SEXP elemSEXP, SEXP objSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type elem(elemSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type obj(objSEXP);
    rcpp_result_gen = Rcpp::wrap(quae_antea_matrix_cpp(elem, obj));
    return rcpp_result_gen;
END_RCPP
}
// gibbs_ad_cpp
Rcpp::NumericMatrix gibbs_ad_cpp(Rcpp::NumericMatrix a, Rcpp::IntegerVector tpq_idx, Rcpp::IntegerMatrix phi, Rcpp::List phiList, Rcpp::IntegerVector taq_idx, Rcpp::IntegerMatrix psi, Rcpp::List psiList, Rcpp::IntegerVector prc_idx);
RcppExport SEXP _eratosthenes_gibbs_ad_cpp(SEXP aSEXP, SEXP tpq_idxSEXP, SEXP phiSEXP, SEXP phiListSEXP, SEXP taq_idxSEXP, SEXP psiSEXP, SEXP psiListSEXP, SEXP prc_idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type a(aSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type tpq_idx(tpq_idxSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type phiList(phiListSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type taq_idx(taq_idxSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type psi(psiSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type psiList(psiListSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type prc_idx(prc_idxSEXP);
    rcpp_result_gen = Rcpp::wrap(gibbs_ad_cpp(a, tpq_idx, phi, phiList, taq_idx, psi, psiList, prc_idx));
    return rcpp_result_gen;
END_RCPP
}
// gibbs_ad_init_cpp
Rcpp::NumericMatrix gibbs_ad_init_cpp(Rcpp::NumericMatrix a, Rcpp::IntegerVector tpq_idx, Rcpp::IntegerMatrix phi, Rcpp::List phiList, Rcpp::IntegerVector taq_idx, Rcpp::IntegerMatrix psi, Rcpp::List psiList, Rcpp::IntegerVector prc_idx);
RcppExport SEXP _eratosthenes_gibbs_ad_init_cpp(SEXP aSEXP, SEXP tpq_idxSEXP, SEXP phiSEXP, SEXP phiListSEXP, SEXP taq_idxSEXP, SEXP psiSEXP, SEXP psiListSEXP, SEXP prc_idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type a(aSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type tpq_idx(tpq_idxSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type phiList(phiListSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type taq_idx(taq_idxSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type psi(psiSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type psiList(psiListSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type prc_idx(prc_idxSEXP);
    rcpp_result_gen = Rcpp::wrap(gibbs_ad_init_cpp(a, tpq_idx, phi, phiList, taq_idx, psi, psiList, prc_idx));
    return rcpp_result_gen;
END_RCPP
}
// gibbs_ad_initial_cpp
Rcpp::NumericVector gibbs_ad_initial_cpp(Rcpp::NumericVector a, Rcpp::IntegerVector tpq_idx, Rcpp::IntegerMatrix phi, Rcpp::List phiList, Rcpp::IntegerVector taq_idx, Rcpp::IntegerMatrix psi, Rcpp::List psiList, Rcpp::IntegerVector prc_idx, int subsample);
RcppExport SEXP _eratosthenes_gibbs_ad_initial_cpp(SEXP aSEXP, SEXP tpq_idxSEXP, SEXP phiSEXP, SEXP phiListSEXP, SEXP taq_idxSEXP, SEXP psiSEXP, SEXP psiListSEXP, SEXP prc_idxSEXP, SEXP subsampleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type tpq_idx(tpq_idxSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type phiList(phiListSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type taq_idx(taq_idxSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type psi(psiSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type psiList(psiListSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type prc_idx(prc_idxSEXP);
    Rcpp::traits::input_parameter< int >::type subsample(subsampleSEXP);
    rcpp_result_gen = Rcpp::wrap(gibbs_ad_initial_cpp(a, tpq_idx, phi, phiList, taq_idx, psi, psiList, prc_idx, subsample));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_eratosthenes_gibbs_ad_use_cpp", (DL_FUNC) &_eratosthenes_gibbs_ad_use_cpp, 3},
    {"_eratosthenes_gibbs_ad_use_init_cpp", (DL_FUNC) &_eratosthenes_gibbs_ad_use_init_cpp, 3},
    {"_eratosthenes_quae_postea_matrix_cpp", (DL_FUNC) &_eratosthenes_quae_postea_matrix_cpp, 2},
    {"_eratosthenes_quae_antea_matrix_cpp", (DL_FUNC) &_eratosthenes_quae_antea_matrix_cpp, 2},
    {"_eratosthenes_gibbs_ad_cpp", (DL_FUNC) &_eratosthenes_gibbs_ad_cpp, 8},
    {"_eratosthenes_gibbs_ad_init_cpp", (DL_FUNC) &_eratosthenes_gibbs_ad_init_cpp, 8},
    {"_eratosthenes_gibbs_ad_initial_cpp", (DL_FUNC) &_eratosthenes_gibbs_ad_initial_cpp, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_eratosthenes(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
