// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// gibbs_ad_cpp
Rcpp::NumericMatrix gibbs_ad_cpp(Rcpp::NumericMatrix a, Rcpp::IntegerVector tpq_idx, Rcpp::IntegerMatrix phi, Rcpp::List phiList, Rcpp::IntegerVector taq_idx, Rcpp::IntegerMatrix psi, Rcpp::List psiList, Rcpp::IntegerVector prc_idx);
RcppExport SEXP _eratosthenes_gibbs_ad_cpp(SEXP aSEXP, SEXP tpq_idxSEXP, SEXP phiSEXP, SEXP phiListSEXP, SEXP taq_idxSEXP, SEXP psiSEXP, SEXP psiListSEXP, SEXP prc_idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type a(aSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type tpq_idx(tpq_idxSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type phiList(phiListSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type taq_idx(taq_idxSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type psi(psiSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type psiList(psiListSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type prc_idx(prc_idxSEXP);
    rcpp_result_gen = Rcpp::wrap(gibbs_ad_cpp(a, tpq_idx, phi, phiList, taq_idx, psi, psiList, prc_idx));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_eratosthenes_gibbs_ad_cpp", (DL_FUNC) &_eratosthenes_gibbs_ad_cpp, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_eratosthenes(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
