# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib eratosthenes
#' @importFrom Rcpp sourceCpp
gibbs_ad_cpp <- function(a, tpq_idx, phi, phiList, taq_idx, psi, psiList, prc_idx) {
    .Call('_eratosthenes_gibbs_ad_cpp', PACKAGE = 'eratosthenes', a, tpq_idx, phi, phiList, taq_idx, psi, psiList, prc_idx)
}

